In [ ]:
import pandas as pd
import numpy as np
import pandas as pd

def importdata(path='iris.csv'):
    data = pd.read_csv(path)
    return data

print(importdata())

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [ ]:
from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
data = importdata()
X = data.iloc[:, :-1]  # all columns except the last one
y = data.iloc[:, -1]   # the last column (assumed to be the target)

# Split the data into training and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set features:\n", X_train)
print("Test set features:\n", X_test)
print("Training set labels:\n", y_train)
print("Test set labels:\n", y_test)

Training set features:
      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]
Test set features:
      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78  

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


# Check if data is loaded successfully
if data is not None:
    print(data.head())  # Print the first few rows to verify

    # Separate features (X) and target (y)
    X = data.iloc[:, :-1]  # all columns except the last one
    y = data.iloc[:, -1]   # the last column (assumed to be the target)

    # Split the data into training and test sets (80% train, 20% test)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

    # Create and train the Decision Tree model
    model = DecisionTreeClassifier(random_state=42)
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy on test set: {accuracy:.2f}")
else:
    print("No data loaded. Please check the file path and format.")

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
Accuracy on test set: 0.98


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy on test set: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy on test set: 0.98
Confusion Matrix:
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
